import type { Metadata } from "next";
import { Geist, Lora, JetBrains_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import { getSession } from "@/lib/session-helper";
import { redirect } from "next/navigation";

const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: {
    default: "AskYourDocs - AI",
    template: "%s | AskYourDocs",
  },
  applicationName: "AskYourDocs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  if (session?.session) redirect("/new");
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
