import type { Metadata } from "next";
import { Geist, Lora, JetBrains_Mono } from "next/font/google";
import "../globals.css";
import { requireUser } from "@/lib/session-helper";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/dashboard/sidebar";
import { Providers } from "@/components/providers";

const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: {
    default: "AskYourDocs - AI",
    template: "%s | AskYourDocs",
  },
  applicationName: "AskYourDocs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await requireUser();

  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased dark`}
      >
        <Providers>
          <SidebarProvider>
            <AppSidebar user={user} />
            <SidebarInset>
              <SidebarTrigger className="px-10 pt-5" />
              <main className="p-10">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
