import type { Metadata } from "next";
import { Geist, Lora, JetBrains_Mono } from "next/font/google";
import "../globals.css";
import { requireUser } from "@/lib/session-helper";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/dashboard/sidebar";
import { Providers } from "@/components/providers";
import { ChatTitle } from "@/components/dashboard/chat/chat-title";

const fontSans = Geist({ subsets: ["latin"], variable: "--font-sans" });
const fontSerif = Lora({ subsets: ["latin"], variable: "--font-serif" });
const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: {
    default: "AskYourDocs - AI",
    template: "%s | AskYourDocs",
  },
  applicationName: "AskYourDocs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const user = await requireUser();

  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased dark`}
      >
        <Providers>
          <SidebarProvider className="h-svh">
            <AppSidebar user={user} />
            <SidebarInset className="min-h-0">
              <div className="flex items-center gap-3 px-10 pt-5 shrink-0">
                <SidebarTrigger />
                <ChatTitle />
              </div>
              <main className="p-10 flex-1 min-h-0 overflow-hidden">
                {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
